version: "3"
services:
  db:
    image: mariadb:10.3
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=myvbc
      - MYSQL_USER=myvbc
      - MYSQL_PASSWORD=myvbc
  web:
    build: .
    links:
      - db
    ports:
      - "8080:8080"
    environment:
      - MYSQL_DB_HOST=db
      - DEVELOPMENT=true
    volumes:
      - "./:/var/www/html/"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - "8081:80"

volumes:
  db-data:
